### ISSUE TITLE
UI modifications..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/cs-materials-react-webclient#33]
Just recapping  yesterday meeting's discussions for changes in UI.

Create 3 categories in main landing page:

View/Explore

Analytics (or Analysis)

Authors

Ensure that typically users will generally stay within these categories (for instance, authoring) and have Back and Save buttons for frequent navigation and saving content when they are working on the pages (especially the Authoring page).

(to Matthew, coordinating with Alec)

**Comment by quaiquai** [comment]
I believe this is done
