### ISSUE TITLE
Solving global state issues

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/cs-materials-react-webclient#52]
There are a few issues in the current website where "global state" does not get kept from one page to the next.

The list of selected materials should essentially be a "global state" of the app so that when going from one page to the next, the state get kept. Some of the components might edit the global state.

This may require to add a few buttons in the left bar to disambiguate one material list from two lists for comparison views.

**Comment by esaule** [comment]
seems like this should solve #47

**Comment by esaule** [comment]
should solve #32

**Comment by quaiquai** [comment]
I now have these materials as a global state from the effect of the new sidebar implementation. just need to make a component for the user to see this global list.

**Comment by quaiquai** [comment]
done
